src/controllers/blog.py
from flask import Blueprint, render_template

blog_bp = Blueprint("blog", __name__, url_prefix="/blog")


@blog_bp.route("/")
def index():
    return render_template("default/blog.jinja")

src/controllers/docs.py
from flask import Blueprint, render_template

docs_bp = Blueprint("docs", __name__, url_prefix="/docs")


@docs_bp.route("/")
def index():
    return render_template("default/docs.jinja")

src/controllers/settings.py
from flask import (
    Blueprint,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_security.utils import hash_password, verify_password

from src import db
from src.forms.ApplicationForm import ApplicationEditForm
from src.forms.settings.AccountForms import (
    ChangeInfoForm,
    ChangePasswordForm,
    EmailForm,
    EmailPreferenceForm,
    PrimaryEmailSelectForm,
)
from src.models import User

settings_bp = Blueprint("settings", __name__, url_prefix="/settings")


@settings_bp.route("/security", methods=["post", "get"])
@login_required
def security():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        current_password = form.current.data
        new_password = form.new.data
        confirmed_password = form.confirm.data

        if new_password != confirmed_password:
            flash("Confirmation password provided doesn't match", "error")
            return redirect(request.referrer)

        if not verify_password(current_password, current_user.password):
            flash("Password provided does not match", "error")
            return redirect(request.referrer)

        current_user.password = hash_password(new_password)
        db.session.commit()

        flash("Password changed successfully", "success")

    return render_template(
        "default/settings/security.jinja", user=current_user, change_password_form=form
    )


@settings_bp.route("/", methods=["post", "get"])
@login_required
def index():
    form = ChangeInfoForm()
    # form=ApplicationEditForm()

    user = User.query.filter_by(id=current_user.id).first()

    if form.validate_on_submit():

        form.populate_obj(user)
        db.session.commit()

        flash("Information updated successfully", "success")
        return redirect(request.referrer)

    elif request.args.get("export_data"):
        # export data into a format
        return make_response()

    elif request.args.get("delete_account"):
        # delete the account and logout
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for("logout"))

    # pre fill the form fields
    form.name.data = user.name
    form.country.data = user.country
    form.city.data = user.city
    form.address.data = user.address
    form.number.data = user.number

    return render_template(
        "default/settings/index.jinja", user=current_user, change_info_form=form
    )


@settings_bp.route("/notifications")
@login_required
def notifications():
    return render_template("default/settings/notifications.jinja", user=current_user)


@settings_bp.route("/emails")
@login_required
def emails():
    email_form = EmailForm()

    if email_form.validate_on_submit():
        pass

    # form to select primary email address
    primary_email_form = PrimaryEmailSelectForm()
    if primary_email_form.validate_on_submit():
        # i should change the current email of the user and set it to the new primary one
        pass

    primary_email_form.elements.choices = [
        (x.label, x.label) for x in current_user.emails
    ]

    # form to select backup email address
    backup_email_form = PrimaryEmailSelectForm()
    if backup_email_form.validate_on_submit():
        pass

    backup_email_form.elements.choices = [
        (x.label, x.label) for x in current_user.emails
    ]

    email_preference_form = EmailPreferenceForm()
    if email_preference_form.validate_on_submit():
        pass

    return render_template(
        "default/settings/emails.jinja",
        user=current_user,
        email_form=email_form,
        primary_email_form=primary_email_form,
        backup_email_form=backup_email_form,
        email_preference_form=email_preference_form,
    )


@settings_bp.route("/billing")
@login_required
def billing():
    return render_template("default/settings/billing.jinja", user=current_user)

src/templates/base.jinja
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block css %}
        {{ webpack['public/css/app.css'] }}
    {% endblock %}
    <title>
        Host Service | {% block title %}{% endblock %}
    </title>
</head>
<body>


    {% block navbar %}
        {% include 'nav.jinja' %}
    {% endblock %}

    {% block body %}{% endblock %}

    {% block js %}
        {{ webpack['public/js/app.js'] }}
        {{ webpack['public/runtime.js'] }}
    {% endblock %}
</body>
</html>

src/templates/base_container.jinja
{% extends "base.jinja"%}

{% block body %}
    <div class="flex maincontainer w-full flex-col justify-center items-center">
        <div class="flex container flex-col w-full md:w-3/4">
            {% block cbody %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

src/templates/nav.jinja
<div class="flex justify-center w-full bg-secondary-700 sticky top-0">
<nav class="flex items-center justify-between flex-wrap bg-secondary-700 p-2 sticky w-full md:w-3/4 top-0 shadow-md ">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
    <a href="{{ url_for('index') }}" class="font-semibold text-xl tracking-tight">Host Control Panel</a>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto ">
    <div class="text-sm lg:flex-grow">
        {% if current_user.is_authenticated %}
          <a href="{{ url_for('dashboard.index') }}" class="nav-item  {{ 'active' if request.endpoint == 'dashboard.index'}} mr-4">Dashboard </a>
        {% endif %}

        <a href="{{ url_for('docs.index') }}" class="nav-item {{ 'active' if request.endpoint == 'docs.index'}} mr-4">Documentation </a>
        <a href="{{ url_for('blog.index') }}" class="nav-item {{ 'active' if request.endpoint == 'blog.index'}}">Blog </a>

    </div>
    <div>
       {% if current_user.is_authenticated %}
            <a href="{{ url_for('logout') }}" class="nav-item ml-auto text-xs hover:underline ">Logout </a>
            <a href="{{ url_for('settings.index') }}" class="nav-item text-xs {{ 'active' if request.endpoint == 'settings.index'}}">Account</a>

            {% if current_user.has_role('admin')  %}
                <a href="{{ url_for('admin.index') }}" class="nav-item ml-auto text-xs hover:underline">Admin </a>
            {% endif %}
       {% else %}
           <a href="{{ url_for('security.login') }}" class="nav-item ml-auto text-xs hover:underline">Login </a>
       {% endif %}
    </div>
  </div>
</nav>
</div>