src/controllers/dashboard.py
from xmlrpc.client import Fault

from flask import Blueprint, abort, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flask_security import roles_required
from sqlalchemy import asc, desc

from src import app, db, supervisor
from src.forms.ApplicationForm import ApplicationEditForm, ApplicationForm
from src.models import Application
from src.models.AppActionHistory import AppActionHistory
from src.utils.HelperClass import AppState
from src.utils.tail import tail

dashboard_bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@dashboard_bp.route("/", methods=["get"])
@login_required
@roles_required("user")
def index():
    appname = request.args.get("appname") or None

    # order the applications of the user // todo
    # current_user.applications

    create_app_form = ApplicationForm()

    ftp_host = app.config.get("FTP_HOST")
    ftp_port = app.config.get("FTP_PORT")

    applications = (
        Application.query.with_parent(current_user)
        .order_by(desc("enabled"), asc("name"))
        .all()
    )

    if appname:

        application = Application.query.filter_by(
            user=current_user, name=appname
        ).first()

        actions_histories = (
            AppActionHistory.query.with_parent(application)
            .order_by(desc("at"))
            .limit(20)
            .all()
        )

        if not application:
            abort(404)

        err_log = None
        out_log = None

        if application.state != AppState.never_started:
            try:
                app_supervisor_name = application.get_supervisor_name()

                err_log: [str] = supervisor.tailProcessStderrLog(
                    app_supervisor_name, True, 4000
                )
                out_log = tail(application.get_out_for_supervisor_log_path(), 1000)

                err_log = err_log[0]
                out_log = "".join(out_log) if type(out_log) == list else out_log

            except OSError as e:
                app.logger.error(e)
                # abort(500)
            except Fault as e:
                app.logger.error(e)
                abort(500)

        return render_template(
            "default/dashboard/select_app.jinja",
            user=current_user,
            applications=applications,
            caform=create_app_form,
            application=application,
            actions_histories=actions_histories,
            AppState=AppState,
            app_out_log=out_log,
            ftp_host=ftp_host,
            ftp_port=ftp_port,
        )

    return render_template(
        "default/dashboard_base.jinja",
        user=current_user,
        applications=applications,
        caform=create_app_form,
        ftp_host=ftp_host,
        ftp_port=ftp_port,
    )


@dashboard_bp.route("/application/edit/<string:appname>", methods=["get", "post"])
def app_edit(appname):
    ftp_host = app.config.get("FTP_HOST")
    ftp_port = app.config.get("FTP_PORT")

    application = Application.query.filter_by(user=current_user, name=appname).first()

    applications = (
        Application.query.with_parent(current_user)
        .order_by(desc("enabled"), asc("name"))
        .all()
    )

    if not application:
        abort(404)

    caform = ApplicationForm()
    edit_app_form = ApplicationEditForm()

    if edit_app_form.validate_on_submit():
        edit_app_form.populate_obj(application)
        db.session.commit()

        return redirect(url_for("dashboard.index", appname=application.name))

    edit_app_form.description.data = application.description
    edit_app_form.callable.data = application.callable
    edit_app_form.domain_name.data = application.domain_name
    edit_app_form.entrypoint.data = application.entrypoint

    return render_template(
        "default/dashboard/edit_app.jinja",
        user=current_user,
        edform=edit_app_form,
        caform=caform,
        application=application,
        applications=applications,
        AppState=AppState,
        ftp_host=ftp_host,
        ftp_port=ftp_port,
    )

src/templates/default/dashboard/app_create.jinja
{% extends "default/dashboard_base.jinja" %}

{% block dashboard_content%}
<form id="caForm"  class="w-full flex flex-col p-3" method="post" action="{{ url_for("dashboard.app_add") }}">
    {{ addform.hidden_tag() }}

        <div class="mb-4">
          <label class="block text-md mb-2" for="name">
            {{ addform.name.label }}
          </label>
          {{ addform.name(class="form-input") }}
            {% for error in addform.name.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="mb-4">
          <label class="block text-md mb-2" for="type">
            {{ addform.type.label }}
          </label>
          {{ addform.type(class="form-input") }}
            {% for error in addform.type.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="mb-4">
          <label class="block text-md mb-2" for="description">
            {{ addform.description.label}}
          </label>
          {{ addform.description(class="form-input") }}
            {% for error in addform.description.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="flex flex-col md:flex-row items-center content-between justify-center w-full md:w-1/5 ml-auto">
            <button id="addformSubmitBtn" class="btn-teal btn w-full" type="submit">
            Save
          </button>
        </div>
</form>
{% endblock %}

src/templates/default/dashboard/edit_app.jinja
{% extends "default/dashboard/select_app.jinja" %}

{% block app_page_body%}
    <form id="defitForm"  class="w-full flex flex-col p-3" method="post" action="{{ url_for("dashboard.app_edit", appname=application.name) }}">
        {{ edform.hidden_tag() }}

        <div class="mb-4">
          <label class="block text-md mb-2" for="domain_name">
            {{ edform.domain_name.label }}
          </label>
          {{ edform.domain_name(class="form-input") }}
            {% for error in edform.domain_name.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="mb-4">
          <label class="block text-md mb-2" for="entrypoint">
            {{ edform.entrypoint.label }}
          </label>
          {{ edform.entrypoint(class="form-input") }}
            {% for error in edform.entrypoint.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="mb-4">
          <label class="block text-md mb-2" for="callable">
            {{ edform.callable.label }}
          </label>
          {{ edform.callable(class="form-input") }}
            {% for error in edform.callable.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}

        </div>

        <div class="mb-4">
          <label class="block text-md mb-2" for="description">
            {{ edform.description.label}}
          </label>
          {{ edform.description(class="form-input") }}
            {% for error in edform.description.errors %}
                <p class="form-error "> {{ error }}</p>
            {% endfor %}
        </div>

        <div class="flex flex-col md:flex-row items-center content-between justify-center w-full md:w-1/5 ml-auto">
            <button id="edformSubmitBtn" class="btn-teal btn w-full" type="submit">
            Save
          </button>
        </div>
</form>
{% endblock %}

src/templates/default/dashboard/select_app.jinja
{% extends 'default/dashboard_base.jinja' %}

{% block dashboard_content %}

    <div class="flex w-full border-b border-grey-300 p-3 ">
        <div class="flex w-1/2 text-2xl text-secondary-500">
            {{ application.name | capitalize}}
        </div>

        <div class="md:w-1/4 ml-auto bg-{{ application.state | state_color }}-500 rounded italic text-center text-white font-bold py-2">
            {{ application.state | state_str | capitalize }}
        </div>
    </div>

    {% block app_page_body %}

        <div class="flex flex-col w-full py-3">
        {% if not application.enabled %}
            <div class="alert info" role="alert">
                <div class="flex">
                    <div class="alert-icon"><i class="fa fa-2x {{ "info" | fa_icon }}"></i></div>
                    <div class="alert-body">
                        <p class="alert-body-title">Information</p>
                        <p class="alert-body-text ">Your application is waiting for validation, you will be noticed when the status is updated</p>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if not application.can_act() %}
            <div class="alert info" role="alert">
                <div class="flex">
                    <div class="alert-icon"><i class="fa fa-2x {{ "info" | fa_icon }}"></i></div>
                    <div class="alert-body">
                        <p class="alert-body-title">Information</p>
                        <p class="alert-body-text ">Upload files into the application folder and set the entrypoint before to be able to control the application</p>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="flex flex-col md:flex-row">
                <a id="startApp" class="app-action" {{ "hidden" if not application.can_start() }}
                   href="{{ url_for('dashboard.app_action', action='start' ,appname=application.name) }}">
                    Start
                </a>
                <a id="reloadApp" class="app-action " {{ "hidden" if not application.can_restart() }}
                   href="{{ url_for('dashboard.app_action', action='restart' ,appname=application.name) }}">
                    Restart
                </a>
                <a id="stopApp" class="app-action" {{ "hidden" if not application.can_stop() }}
                   href="{{ url_for('dashboard.app_action', action='stop' ,appname=application.name) }}">
                    Stop
                </a>
                <button id="stopApp" class="app-action " {{ "hidden" if not application.can_execute_command() }}>
                    Install requirements
                </button>
            </div>

            <div class="flex flex-row w-full">
                <form action="{{ url_for('dashboard.app_install_requirements', appname=application.name) }}" method="post" class="w-full">
                    <div class="flex items-center border-b border-b-2 border-secondary-700 py-1 mx-1">
                        <input type="text" class="w-full appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py1 px-2 leading-tight focus:outline-none" placeholder="Requirement file name" name="req_file_name" required >
    {#                    <input type="text" class="form-input" placeholder="Enter the command you want to execute">#}
                        <button class="bg-secondary-700 hover:bg-grey-700 text-sm border-2 text-white py-1 px-2 rounded" type="submit">Execute</button>
                    </div>
                </form>
            </div>
        {% endif %}

        </div>

        <div class="section section-details">
            <div class="section-header flex-row">
                <div class="">Details</div>
                <a href="{{ url_for("dashboard.app_edit", appname=application.name) }}" class="ml-auto underline"><i class="fa fa-x fa-edit"></i></a>
            </div>
            <div class="section-body flex-col " >

            <table class="text-left w-full border-collapse">
              <tbody>
                <tr class="hover:bg-grey-100">
                  <td class="py-4 px-6 border-b border-grey-100">Name</td>
                  <td class="py-4 px-6 border-b border-grey-100">{{ application.name }}</td>
                </tr>
                <tr class="hover:bg-grey-100">
                  <td class="py-4 px-6 border-b border-grey-100">Language</td>
                  <td class="py-4 px-6 border-b border-grey-100">{{ application.type.value | capitalize }}</td>
                </tr>
                <tr class="hover:bg-grey-100">
                  <td class="py-4 px-6 border-b border-grey-100">Entrypoint</td>
                  <td class="py-4 px-6 border-b border-grey-100">{{ application.entrypoint or None }}</td>
                </tr>
                <tr class="hover:bg-grey-100">
                  <td class="py-4 px-6 border-b border-grey-100">Domaine name</td>
                  <td class="py-4 px-6 border-b border-grey-100">
                      {% if application.domain_name %}
                          <a href="http://{{ application.domain_name }}" target="_blank">{{ application.domain_name }}</a>
                      {% else %}
                          {{ None }}
                      {% endif %}
                  </td>
                </tr>
                <tr class="hover:bg-grey-100">
                  <td class="py-4 px-6 border-b-0 border-grey-100">Enabled</td>
                  <td class="py-4 px-6 border-b-0 border-grey-100">{{ application.enabled }}</td>
                </tr>
              </tbody>
            </table>

            </div>
        </div>

        <div class="section section-history">
            <div class="section-header">Action history</div>
            <div class="section-body " >
            {% if actions_histories | count >= 1 %}
                <table class="text-let w-full bg-grey-100 border-collapse">
                    <thead>
                        <tr class="hover:bg-grey-300 border-b border-grey-300">
                            <td class="py-0 px-2 text-center">On State</td>
                            <td class="py-0 px-2 text-center">Action</td>
                            <td class="py-0 px-2 text-center">Lead to</td>
                            <td class="py-0 px-2 text-center">At</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for history in actions_histories %}
                        <tr class="hover:bg-grey-300 border-b border-grey-300">
                            <td class="py-0 px-2 text-center text-{{ history.old_state | state_color }}-400">{{ history.old_state | state_str }}</td>
                            <td class="py-0 px-2 text-center ">{{ history.action }}</td>
                            <td class="py-0 px-2 text-center text-{{ history.new_state | state_color }}-400">{{ history.new_state | state_str}}</td>
                            <td class="py-0 px-2 text-center text-secondary-300">{{ history.at | datetime("full") }}</td>
                        </tr>
                {% endfor %}
                    </tbody>
                </table>
            {% else %}
                    <div class="w-full text-center font-mono">
                        No history.
                    </div>
            {% endif %}
            </div>
        </div>

        <div class="section section-log">
            <div class="section-header">Logs</div>
            <div class="section-body " >
                {% if app_out_log != None %}
                    <code class="overflow-auto w-full text-sm leading-tight h-64">
                        <pre>
{{ app_out_log }}
                        </pre>
                    </code>
                {% else %}
                    <div class="w-full text-center font-mono">
                        No logs.
                    </div>
                {% endif %}
            </div>
        </div>
    {% endblock %}

{% endblock %}


{% block sideinfo %}
    <div class="flex-col flex w-full md:w-full mb-5 shadow-md">
            <div class="flex flex-row w-full w-full rounded-t p-3 bg-secondary-500 text-white text-xl italic">
                Ftp Credentials
{#                #}
            </div>

            <div class="flex flex-col w-full border border-t-0 border-grey-300 rounded-b">
                <table class="text-left w-full bg-grey-100 border-collapse">
                  <tbody>
                    <tr class="hover:bg-grey-300 border-b border-grey-300">
                      <td class="py-2 px-2 ">Host:</td>
                      <td class="py-2 px-2 ">{{ ftp_host }}</td>
                    </tr>
                    <tr class="hover:bg-grey-300 border-b border-grey-300">
                      <td class="py-2 px-2 ">Port:</td>
                      <td class="py-2 px-2 ">{{ ftp_port }}</td>
                    </tr>
                    <tr class="hover:bg-grey-300 border-b border-grey-300">
                      <td class="py-2 px-2 ">Username:</td>
                      <td class="py-2 px-2 ">{{ user.username }}:{{ application.name }}</td>
                    </tr>
                    <tr class="hover:bg-grey-300">
                      <td class="py-2 px-2 ">Password:</td>
                      <td class="py-2 px-2 ">Your current password</td>
                    </tr>
                  </tbody>
                </table>
            </div>

        </div>
{% endblock %}